/*
 * UIAboutPanel
 * This code is generated by code. Do not modify it。
 */
using System;
using UnityEngine;
using UnityEngine.UI;
using TMPro;
using VirtualList;

[RequireComponent(typeof(Canvas))]
[RequireComponent(typeof(GraphicRaycaster))]
public partial class UIAboutPanel : UIPanelBase
{
    public static string PanelName => "About";

    [NonSerialized]
    public TextMeshProUGUI txtTitle;
    [NonSerialized]
    public Button btnClose;
    [NonSerialized]
    public TextMeshProUGUI txtContent;

    protected override void OnPreInit()
    {
        txtTitle = FindBindComponent<TextMeshProUGUI>("g:txtTitle");
        btnClose = FindBindComponent<Button>("g:btnClose");
        txtContent = FindBindComponent<TextMeshProUGUI>("g:txtContent");

    }
}