/*
 * UIMainHeaderPanel
 * This code is generated by code. Do not modify it。
 */
using System;
using UnityEngine;
using UnityEngine.UI;
using TMPro;
using VirtualList;

[RequireComponent(typeof(Canvas))]
[RequireComponent(typeof(GraphicRaycaster))]
public partial class UIMainHeaderPanel : UIPanelBase
{
    public static string PanelName => "MainHeader";

    [NonSerialized]
    public RectTransform goCmdRoot;
    [NonSerialized]
    public Button btnCmdOpen;
    [NonSerialized]
    public Button btnCmdSave;
    [NonSerialized]
    public Button btnCmdAbout;
    [NonSerialized]
    public TextMeshProUGUI txtVersion;

    protected override void OnPreInit()
    {
        goCmdRoot = FindBindComponent<RectTransform>("g:goCmdRoot");
        btnCmdOpen = FindBindComponent<Button>("g:btnCmdOpen");
        btnCmdSave = FindBindComponent<Button>("g:btnCmdSave");
        btnCmdAbout = FindBindComponent<Button>("g:btnCmdAbout");
        txtVersion = FindBindComponent<TextMeshProUGUI>("g:txtVersion");

    }
}