/*
 * UIMessageScrollBoxPanel
 * This code is generated by code. Do not modify it。
 */
using System;
using UnityEngine;
using UnityEngine.UI;
using TMPro;
using VirtualList;
using UnityEngine.UI.Extensions;

[RequireComponent(typeof(Canvas))]
[RequireComponent(typeof(GraphicRaycaster))]
public partial class UIMessageScrollBoxPanel : UIPanelBase
{
    public static string PanelName => "MessageScrollBox";

    [NonSerialized]
    public TextMeshProUGUI txtTitle;
    [NonSerialized]
    public RectTransform goScrollRoot;
    [NonSerialized]
    public RectTransform goContentRoot;
    [NonSerialized]
    public TextMeshProUGUI txtContent;
    [NonSerialized]
    public Button btnOk;
    [NonSerialized]
    public TextMeshProUGUI txtOk;

    protected override void OnPreInit()
    {
        txtTitle = FindBindComponent<TextMeshProUGUI>("g:txtTitle");
        goScrollRoot = FindBindComponent<RectTransform>("g:goScrollRoot");
        goContentRoot = FindBindComponent<RectTransform>("g:goContentRoot");
        txtContent = FindBindComponent<TextMeshProUGUI>("g:txtContent");
        btnOk = FindBindComponent<Button>("g:btnOk");
        txtOk = FindBindComponent<TextMeshProUGUI>("g:txtOk");

    }
}