/*
 * UIModCreateAvatarEditorPanel
 * This code is generated by code. Do not modify it。
 */
using System;
using UnityEngine;
using UnityEngine.UI;
using TMPro;
using VirtualList;

[RequireComponent(typeof(Canvas))]
[RequireComponent(typeof(GraphicRaycaster))]
public partial class UIModCreateAvatarEditorPanel : UIPanelBase
{
    public static string PanelName => "ModCreateAvatarEditor";


    protected override void OnPreInit()
    {

    }
}