/*
 * UIModConfigEditorPanel
 * This code is generated by code. Do not modify it。
 */
using System;
using UnityEngine;
using UnityEngine.UI;
using TMPro;
using VirtualList;

[RequireComponent(typeof(Canvas))]
[RequireComponent(typeof(GraphicRaycaster))]
public partial class UIModConfigEditorPanel : UIPanelBase
{
    public static string PanelName => "ModConfigEditor";

    [NonSerialized]
    public TextMeshProUGUI txtModName;
    [NonSerialized]
    public TMP_InputField inModName;
    [NonSerialized]
    public TextMeshProUGUI txtModAuthor;
    [NonSerialized]
    public TMP_InputField inModAuthor;
    [NonSerialized]
    public TextMeshProUGUI txtModVersion;
    [NonSerialized]
    public TMP_InputField inModVersion;
    [NonSerialized]
    public TextMeshProUGUI txtModDesc;
    [NonSerialized]
    public TMP_InputField inModDesc;

    protected override void OnPreInit()
    {
        txtModName = FindBindComponent<TextMeshProUGUI>("g:txtModName");
        inModName = FindBindComponent<TMP_InputField>("g:inModName");
        txtModAuthor = FindBindComponent<TextMeshProUGUI>("g:txtModAuthor");
        inModAuthor = FindBindComponent<TMP_InputField>("g:inModAuthor");
        txtModVersion = FindBindComponent<TextMeshProUGUI>("g:txtModVersion");
        inModVersion = FindBindComponent<TMP_InputField>("g:inModVersion");
        txtModDesc = FindBindComponent<TextMeshProUGUI>("g:txtModDesc");
        inModDesc = FindBindComponent<TMP_InputField>("g:inModDesc");

    }
}