/*
 * UIModCommonEditorFramePanel
 * This code is generated by code. Do not modify it。
 */
using System;
using UnityEngine;
using UnityEngine.UI;
using TMPro;
using VirtualList;
using UnityEngine.UI.Extensions;

[RequireComponent(typeof(Canvas))]
[RequireComponent(typeof(GraphicRaycaster))]
public partial class UIModCommonEditorFramePanel : UIPanelBase
{
    public static string PanelName => "ModCommonEditorFrame";


    protected override void OnPreInit()
    {

    }
}