/*
 * UIModAffixEditorPanel
 * This code is generated by code. Do not modify it。
 */
using System;
using UnityEngine;
using UnityEngine.UI;
using TMPro;
using VirtualList;

[RequireComponent(typeof(Canvas))]
[RequireComponent(typeof(GraphicRaycaster))]
public partial class UIModAffixEditorPanel : UIPanelBase
{
    public static string PanelName => "ModAffixEditor";


    protected override void OnPreInit()
    {

    }
}