/*
 * UISeidEditorBoxPanel
 * This code is generated by code. Do not modify it。
 */
using System;
using UnityEngine;
using UnityEngine.UI;
using TMPro;
using VirtualList;

[RequireComponent(typeof(Canvas))]
[RequireComponent(typeof(GraphicRaycaster))]
public partial class UISeidEditorBoxPanel : UIPanelBase
{
    public static string PanelName => "SeidEditorBox";

    [NonSerialized]
    public TextMeshProUGUI txtTitle;
    [NonSerialized]
    public RectTransform goEditorDrawers;
    [NonSerialized]
    public RectTransform goDrawerRoot;
    [NonSerialized]
    public Button btnOk;
    [NonSerialized]
    public TextMeshProUGUI txtOk;

    protected override void OnPreInit()
    {
        txtTitle = FindBindComponent<TextMeshProUGUI>("g:txtTitle");
        goEditorDrawers = FindBindComponent<RectTransform>("g:goEditorDrawers");
        goDrawerRoot = FindBindComponent<RectTransform>("g:goDrawerRoot");
        btnOk = FindBindComponent<Button>("g:btnOk");
        txtOk = FindBindComponent<TextMeshProUGUI>("g:txtOk");

    }
}