/*
 * UITestPanel
 * This code is generated by code. Do not modify it。
 */
using System;
using UnityEngine;
using UnityEngine.UI;
using TMPro;
using VirtualList;

[RequireComponent(typeof(Canvas))]
[RequireComponent(typeof(GraphicRaycaster))]
public partial class UITestPanel : UIPanelBase
{
    public static string PanelName => "Test";

    [NonSerialized]
    public Image bgGround;
    [NonSerialized]
    public Image bgTop;
    [NonSerialized]
    public Button btnA;
    [NonSerialized]
    public TextMeshProUGUI txtA;
    [NonSerialized]
    public TMP_InputField inTest;
    [NonSerialized]
    public Button btnClose;
    [NonSerialized]
    public Toggle tglTest;
    [NonSerialized]
    public Slider sliTest;
    [NonSerialized]
    public Dropdown ddlTest;

    protected override void OnPreInit()
    {
        bgGround = FindBindComponent<Image>("g:bgGround");
        bgTop = FindBindComponent<Image>("g:bgTop");
        btnA = FindBindComponent<Button>("g:btnA");
        txtA = FindBindComponent<TextMeshProUGUI>("g:txtA");
        inTest = FindBindComponent<TMP_InputField>("g:inTest");
        btnClose = FindBindComponent<Button>("g:btnClose");
        tglTest = FindBindComponent<Toggle>("g:tglTest");
        sliTest = FindBindComponent<Slider>("g:sliTest");
        ddlTest = FindBindComponent<Dropdown>("g:ddlTest");

    }
}