/*
 * UIComTextDrawer
 * This code is generated by code. Do not modify it。
 */
using System;
using UnityEngine;
using UnityEngine.UI;
using TMPro;
using VirtualList;

public partial class UIComTextDrawer : UIComBase
{
    public static string ComName => "textDrawer";

    [NonSerialized]
    public TextMeshProUGUI txtTitle;

    protected override void OnPreInit()
    {
        txtTitle = FindBindComponent<TextMeshProUGUI>("g:txtTitle");

    }
}