/*
 * UIComSeidListItem
 * This code is generated by code. Do not modify it。
 */
using System;
using UnityEngine;
using UnityEngine.UI;
using TMPro;
using VirtualList;

public partial class UIComSeidListItem : UIComBase
{
    public static string ComName => "seidListItem";

    [NonSerialized]
    public Button btnEdit;
    [NonSerialized]
    public TextMeshProUGUI txtTitle;
    [NonSerialized]
    public Button btnWarning;
    [NonSerialized]
    public Button btnRemove;

    protected override void OnPreInit()
    {
        btnEdit = FindBindComponent<Button>("g:btnEdit");
        txtTitle = FindBindComponent<TextMeshProUGUI>("g:txtTitle");
        btnWarning = FindBindComponent<Button>("g:btnWarning");
        btnRemove = FindBindComponent<Button>("g:btnRemove");

    }
}