/*
 * UIBackgroundPanel
 * This code is generated by code. Do not modify it。
 */
using System;
using UnityEngine;
using UnityEngine.UI;
using TMPro;

[RequireComponent(typeof(Canvas))]
[RequireComponent(typeof(GraphicRaycaster))]
public partial class UIBackgroundPanel : UIPanelBase
{
    public static string PanelName => "Background";


    protected override void OnPreInit()
    {

    }
}