/*
 * UIConfirmBoxPanel
 * This code is generated by code. Do not modify it。
 */
using System;
using UnityEngine;
using UnityEngine.UI;
using TMPro;
using VirtualList;

[RequireComponent(typeof(Canvas))]
[RequireComponent(typeof(GraphicRaycaster))]
public partial class UIConfirmBoxPanel : UIPanelBase
{
    public static string PanelName => "ConfirmBox";

    [NonSerialized]
    public TextMeshProUGUI txtTitle;
    [NonSerialized]
    public TextMeshProUGUI txtContent;
    [NonSerialized]
    public Button btnOk;
    [NonSerialized]
    public TextMeshProUGUI txtOk;
    [NonSerialized]
    public Button btnCancel;
    [NonSerialized]
    public TextMeshProUGUI txtCancel;

    protected override void OnPreInit()
    {
        txtTitle = FindBindComponent<TextMeshProUGUI>("g:txtTitle");
        txtContent = FindBindComponent<TextMeshProUGUI>("g:txtContent");
        btnOk = FindBindComponent<Button>("g:btnOk");
        txtOk = FindBindComponent<TextMeshProUGUI>("g:txtOk");
        btnCancel = FindBindComponent<Button>("g:btnCancel");
        txtCancel = FindBindComponent<TextMeshProUGUI>("g:txtCancel");

    }
}