/*
 * UIMessageBoxPanel
 * This code is generated by code. Do not modify it。
 */
using System;
using UnityEngine;
using UnityEngine.UI;
using TMPro;

[RequireComponent(typeof(Canvas))]
[RequireComponent(typeof(GraphicRaycaster))]
public partial class UIMessageBoxPanel : UIPanelBase
{
    public static string PanelName => "MessageBox";

    [NonSerialized]
    public TextMeshProUGUI txtTitle;
    [NonSerialized]
    public TextMeshProUGUI txtContent;
    [NonSerialized]
    public Button btnOk;
    [NonSerialized]
    public TextMeshProUGUI txtOk;

    protected override void OnPreInit()
    {
        txtTitle = FindBindComponent<TextMeshProUGUI>("g:txtTitle");
        txtContent = FindBindComponent<TextMeshProUGUI>("g:txtContent");
        btnOk = FindBindComponent<Button>("g:btnOk");
        txtOk = FindBindComponent<TextMeshProUGUI>("g:txtOk");

    }
}