/*
 * UISelectBoxPanel
 * This code is generated by code. Do not modify it。
 */
using System;
using UnityEngine;
using UnityEngine.UI;
using TMPro;
using VirtualList;
using UnityEngine.UI.Extensions;

[RequireComponent(typeof(Canvas))]
[RequireComponent(typeof(GraphicRaycaster))]
public partial class UISelectBoxPanel : UIPanelBase
{
    public static string PanelName => "SelectBox";

    [NonSerialized]
    public TextMeshProUGUI txtTitle;
    [NonSerialized]
    public TextMeshProUGUI txtContent;
    [NonSerialized]
    public Button btnFunc1;
    [NonSerialized]
    public TextMeshProUGUI txtFunc1;
    [NonSerialized]
    public Button btnFunc2;
    [NonSerialized]
    public TextMeshProUGUI txtFunc2;
    [NonSerialized]
    public Button btnCancel;
    [NonSerialized]
    public TextMeshProUGUI txtCancel;

    protected override void OnPreInit()
    {
        txtTitle = FindBindComponent<TextMeshProUGUI>("g:txtTitle");
        txtContent = FindBindComponent<TextMeshProUGUI>("g:txtContent");
        btnFunc1 = FindBindComponent<Button>("g:btnFunc1");
        txtFunc1 = FindBindComponent<TextMeshProUGUI>("g:txtFunc1");
        btnFunc2 = FindBindComponent<Button>("g:btnFunc2");
        txtFunc2 = FindBindComponent<TextMeshProUGUI>("g:txtFunc2");
        btnCancel = FindBindComponent<Button>("g:btnCancel");
        txtCancel = FindBindComponent<TextMeshProUGUI>("g:txtCancel");

    }
}