/*
 * UIComTglListItem
 * This code is generated by code. Do not modify it。
 */
using System;
using UnityEngine;
using UnityEngine.UI;
using TMPro;

public partial class UIComTglListItem : UIComBase
{
    public static string ComName => "tglListItem";

    [NonSerialized]
    public Toggle tglTab;
    [NonSerialized]
    public TextMeshProUGUI txtTab;

    protected override void OnPreInit()
    {
        tglTab = FindBindComponent<Toggle>("g:tglTab");
        txtTab = FindBindComponent<TextMeshProUGUI>("g:txtTab");

    }
}