/*
 * UIComTextWithContentDrawer
 * This code is generated by code. Do not modify it。
 */
using System;
using UnityEngine;
using UnityEngine.UI;
using TMPro;
using VirtualList;

public partial class UIComTextWithContentDrawer : UIComBase
{
    public static string ComName => "textWithContentDrawer";

    [NonSerialized]
    public TextMeshProUGUI txtTitle;
    [NonSerialized]
    public TextMeshProUGUI txtContent;

    protected override void OnPreInit()
    {
        txtTitle = FindBindComponent<TextMeshProUGUI>("g:txtTitle");
        txtContent = FindBindComponent<TextMeshProUGUI>("g:txtContent");

    }
}